stages:
  - test
  - deploy
  - trigger

image: node:lts-alpine
cache:
  key: ${CI_COMMIT_REF_SLUG}
before_script:
  - npm install

test:
  image: postgres:12
  variables:
    RABBITMQ_DEFAULT_USER: guest
    RABBITMQ_DEFAULT_PASS: guest
    RABBITMQ_URL: amqp://guest:guest@127.0.0.1:5672
    DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/postgres
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    NODE_ENV: development
  services:
    - rabbitmq
    - postgres
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y curl
    - curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
    - apt-get install -y nodejs gcc g++ make
    - npm install
  script:
    - npm test

lint:
  stage: test
  script:
    - npx eslint src

audit:
  stage: test
  script:
    - npm audit
  allow_failure: true

deploy image:
  stage: deploy
  image: registry.yusufali.ca/containers/kaniko
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - echo "Building $WRITE_REGISTRY_URL/$CI_PROJECT_PATH"
  script:
    - export IMAGE="$WRITE_REGISTRY_URL/$CI_PROJECT_PATH"
    - build

deploy cluster:
  stage: trigger
  image: curlimages/curl
  only:
    - master
  before_script:
    - echo "About to deploy to cluster"
  script:
    - "curl -X POST -F token=$TOKEN -F ref=master https://$CI_SERVER_HOST/api/v4/projects/25/trigger/pipeline"
