FROM node:lts-alpine

WORKDIR /app
COPY src src
COPY tsconfig.json .
COPY nodemon.json .
COPY package.json .
COPY package-lock.json .

# Install build tool chain
RUN apk add --no-cache --virtual python make g++
RUN npm install && npm install -g nodemon

ENV NODE_ENV development
USER node
CMD ["nodemon"]